apiVersion: apps/v1
kind: Deployment
metadata:
    name: petclinic-deployment
    labels:
       app: petclinic-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
   matchLabels:
     app: petclinic-app
  template:
   metadata:
     labels:
       app: petclinic-app
   spec:
     containers:
     - name: petclinic
       image: pooja24n/petclinic
       ports:
        - containerPort: 8080
       env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: password
       envFrom:
        - secretRef:
            name: mysql-user-creds
       volumeMounts:
          - name: petclinic-config
            mountPath: "/etc/mysql/conf.d"
     volumes:
      - configMap:
          name: petclinic-config
          items:
            - key: max_allowed_packet.cnf
              path: max_allowed_packet.cnf
        name: petclinic-config
        
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
   type: NodePort
   selector:
       app: petclinic-app
   ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
